### ISSUE TITLE
[Fix] The title of the website

### ISSUE THREAD

**Issue by chaitanyarora** [hereisSwapnil/ExamTime#20] opened 2024-05-10 05:11 UTC
Curretnly the website shows Vite + React.

**Comment by chaitanyarora** [comment] 2024-05-10 06:00
Thankyou for assigning me this issue!
On it sir!

**Comment by chaitanyarora** [comment] 2024-05-10 10:55
Sir i have raise a PR [here](https://github.com/hereisSwapnil/ExamTime/pull/24) is the link to that PR.

**Comment by ira-mane** [comment] 2024-05-11 04:53
If the issue is not resolved ,Can I work on it ? @hereisSwapnil

**Comment by Aman0413** [comment] 2024-05-11 09:58
please assign to me.

**Closed** 2024-05-11 14:27 UTC
Labels: level1, gssoc
